# Welcome to your law firm website. Change the values in this file to configure your site. 

# The name of your law firm
title: "Fourcand"

# The email address of your law firm. Messages sent using the contact form will arrive at this address.
email: "info@ftkpavocats.com"

# The phone number of your law firm. This will be displayed on the website.
phone: "+1 514 297-3511"

# The description of your website. This will be displayed in the footer of the website
description: >- # this means to ignore newlines until "baseurl:"
  Fourcand Avocats 

# The tagline of your website. This will be displayed on the home page of your website
tagline: ""

# The address of your firm. This will be displayed in the footer of your website
address_1: ""
address_2: ""

# It would not be a legal website without a disclaimer! This will be displayed in the footer of your website
disclaimer: ""

# The secondary tagline of your website. This will be displayed on the home page of your website, under the primary tagline
secondary_tagline: ""

# The url of the main image of your website. This image is displayed front and center on the home page. 
background_image: assets/images/Home.jpg

repository: ""

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  - posts

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
